Config files and note directories

diff --git a/clint b/clint
--- a/clint
+++ b/clint
@@ -1,23 +1,85 @@
 #! /bin/bash
 
+CONFIG_PATH="$HOME/.config/clint"
+
+# Get the path where the script is placed {{{
+
+getscriptdir () {
+    # Use $0 to get the script's physical path.
+    cd "${0%/*}" || exit
+    script_dir=${0##*/}
+
+    # Iterate down a (possible) chain of symlinks.
+    while [ -L "$script_dir" ]; do
+        script_dir="$(readlink "$script_dir")"
+        cd "${script_dir%/*}" || exit
+        script_dir="${script_dir##*/}"
+    done
+
+    # Final directory
+    script_dir="$(pwd -P)"
+}
+# }}}
+
+# Print usage {{{
 usage() {
-  echo "Usage: clint new <note title>"
+  echo "Usage: clint <command>"
+  echo ""
+  echo "Where \"command\" can be:"
+  echo "  new <title> - Creates or modifies a note"
+  echo "  log         - Display git log"
 }
+# }}}
 
+# Install config {{{
+install() {
+  mkdir -p "$CONFIG_PATH"
+  getscriptdir
+  cp "$script_dir/config/config" "$CONFIG_PATH"
+}
+# }}}
+
+# Create note {{{
 newnote() {
-  [[ ! -d ".git" ]] && git init # Create git repo if it does not exist
   filename="$(echo -n $1 | tr ' ' '-').md"
-  $VISUAL "$filename" && git add "$filename" && git commit -m "$filename" # Edit, save, commit
+  [[ ! -d "$notes_dir/.git" ]] && git init "$notes_dir" # Create git repo if it does not exist
+  message="Created"
+  [[ -f "$notes_dir/$filename" ]] && message="Modified"
+  cd "$notes_dir"
+  $VISUAL "$notes_dir/$filename" && git add "$notes_dir/$filename" && git commit -m "$1" # Edit, save, commit
+    echo "$message note at \"$notes_dir/$filename\""
+}
+# }}}
+
+# Load config {{{
+
+[[ ! -d "$CONFIG_PATH" ]] && install
+source "$CONFIG_PATH/config"
+if [[ ! -d "$notes_dir" ]]; then
+  mkdir -p "$notes_dir"
+  echo "Created notes dir \"$notes_dir\""
+fi
+
+# }}}
+
+fail() {
+  usage
+  exit 1
 }
 
-if [[ $# -lt 2 ]]; then
-  usage
-  exit 1
-fi
+[[ $# -eq 0 ]] && fail
 
-if [[ $1 -ne "new" ]]; then
-  usage
-  exit 1
-fi
-
-newnote "${@:2}"
+case $1 in
+  new)
+    [[ $# -eq 1 ]] && fail
+    newnote "${@:2}"
+    ;;
+  log)
+    cd "$notes_dir"
+    git log
+    ;;
+  *)
+    usage
+    exit 1
+    ;;
+esac
